name: Publish latest imaptest

on:
  pull_request:
  push:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build_debian:
    strategy:
      matrix:
        include:
          - os_name: ubuntu-24.04
            os_image: ubuntu-24.04
            arch: x86_64
            aliases: '["debian-13"]'
          - os_name: ubuntu-22.04
            os_image: ubuntu-22.04
            arch: x86_64
            aliases: '["debian-12"]'
          - os_name: ubuntu-20.04
            os_image: ubuntu-20.04
            arch: x86_64
          - os_name: debian-11
            os_image: ubuntu-20.04
            arch: x86_64
          - os_name: debian-12
            os_image: ubuntu-22.04
            arch: x86_64
          - os_name: ubuntu-24.04
            os_image: ubuntu-24.04-arm
            arch: arm64
            aliases: '["debian-13"]'
    runs-on: ${{ matrix.os_image }}
    steps:
      - name: Checkout imaptest
        uses: actions/checkout@v4
        with:
          path: imaptest
      - name: Checkout dovecot
        id: checkout_dovecot
        uses: actions/checkout@v4
        with:
          repository: dovecot/core
          path: core
      - name: Cache dovecot build
        id: cache-dovecot
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/core
          key: ${{ runner.os }}-${{ matrix.arch }}-dovecot-${{ steps.checkout_dovecot.outputs.commit }}
      - name: Install gettext (missing from GH Actions image)
        run: |
          sudo apt install -y gettext
      - name: Build dovecot libraries
        if: steps.cache-dovecot.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/core
        run: |
          ./autogen.sh
          ./configure
          make -j8
      - name: Build imaptest
        working-directory: ${{ github.workspace }}/imaptest
        run: |
          ./autogen.sh
          ./configure --with-dovecot=../core
          make -j8
      - name: Strip imaptest
        run: |
          strip --strip-all imaptest/src/imaptest
      - name: Rename artifact
        run: |
          mv imaptest/src/imaptest imaptest-${{ matrix.arch }}-${{ matrix.os_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}-${{ matrix.os_name }}
          path: imaptest-${{ matrix.arch }}-${{ matrix.os_name }}
  build_rhel:
    strategy:
      matrix:
        include:
          - os: rhel8
            container: registry.access.redhat.com/ubi8/ubi
            stream: https://vault.centos.org/8-stream
            aliases: '["debian-11","ubuntu-20.04"]'
          - os: rhel9
            container: registry.access.redhat.com/ubi9/ubi
            stream: https://mirror.stream.centos.org/9-stream/
            aliases:  '[]'
          - os: rhel10
            container: registry.access.redhat.com/ubi10/ubi
            stream: https://mirror.stream.centos.org/10-stream/
            aliases:  '[]'
    runs-on: ubuntu-latest
    container:
        image: ${{ matrix.container }}
    steps:
      - name: Checkout imaptest
        uses: actions/checkout@v4
        with:
          path: imaptest
      - name: Checkout dovecot
        id: checkout_dovecot
        uses: actions/checkout@v4
        with:
          repository: dovecot/core
          path: core
      - name: Cache dovecot build
        id: cache-dovecot
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/core
          key: rhel-${{ matrix.os }}-${{ steps.checkout_dovecot.outputs.commit }}
      - name: Install build dependencies
        run: |
          dnf makecache
          dnf install -y gcc gcc-c++ make automake autoconf libtool pkgconf-pkg-config gettext zlib-devel openssl-devel autoconf-archive diffutils file wget git perl-version python3
      - name: Add repositories
        run: |
          cat <<EOF > /etc/yum.repos.d/stream.repo
          [${{ matrix.os }}-stream_baseos]
          name = ${{ matrix.os }} - stream baseos
          baseurl = ${{ matrix.stream }}/BaseOS/x86_64/os
          gpgcheck = 0
          enabled = 1
          [${{ matrix.so }}-stream_appstream]
          name = ${{ matrix.os }} - stream appstream
          baseurl = ${{ matrix.stream }}/AppStream/x86_64/os
          gpgcheck = 0
          enabled = 1
          EOF
      - name: Install more build dependencies
        run: |
          dnf makecache
          dnf install -y gettext-devel bison flex
      - name: Force-enable pic
        run: |
          sed -s -i -e 's/LT_INIT/LT_INIT([pic-only])/' core/configure.ac
      - name: Build dovecot libraries
        if: steps.cache-dovecot.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/core
        run: |
          env VERSION=0.0.0 ./autogen.sh
          ./configure
          make -j8
      - name: Build imaptest
        working-directory: ${{ github.workspace }}/imaptest
        run: |
          env VERSION=0.0.0 ./autogen.sh
          ./configure --with-dovecot=../core
          make -j8
      - name: Strip imaptest
        run: |
          strip --strip-all imaptest/src/imaptest
      - name: Rename artifact
        run: |
          for n in ${{ join(fromJSON(matrix.aliases), ' ') }}; do cp imaptest/src/imaptest "imaptest-$(uname -m)-$n"; done
          mv imaptest/src/imaptest imaptest-$(uname -m)-${{ matrix.os }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-x86_64-${{ matrix.os }}
          path: imaptest-x86_64-*
  publish:
    if: ${{ github.repository == 'dovecot/imaptest' && github.ref == 'refs/heads/main' }}
    needs:
      - build_debian
      - build_rhel
    runs-on: ubuntu-latest
    steps:
      - name: Download items
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - name: List files
        run: |
          find
      - name: Generate SHA256SUMS.txt
        working-directory: build
        run: |
          sha256sum imaptest-* > SHA256SUMS.txt
      - name: Update latest Release
        uses: andelf/nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: 'ImapTest Latest Release'
          draft: false
          body: |
            ImapTest semi-static builds. These work on most machines with matching
            libc. These usually work with Debian as well.
          files: |
            build/imaptest-*
            build/SHA256SUMS.txt
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build_debian
    steps:
      - name: Checkout imaptest source
        uses: actions/checkout@v4
      - name: Download imaptest binary
        uses: actions/download-artifact@v4
        with:
          name: build-x86_64-ubuntu-24.04
          path: .
      - name: Prepare dovecot config
        run: |
          cat <<EOF > dovecot.conf
          protocols = imap
          ssl = no
          disable_plaintext_auth = no
          mail_location = mbox:~/mail:INBOX=/var/mail/%u
          passdb {
            driver = passwd-file
            args = /etc/dovecot/users
          }
          userdb {
            driver = static
            args = uid=vmail gid=vmail home=/var/mail/%u
          }
          EOF
          echo "imaptest:{PLAIN}imaptest" > users
      - name: Run dovecot container
        run: |
          docker run -d --name dovecot -p 1430:143 \
            -v $(pwd)/dovecot.conf:/etc/dovecot/dovecot.conf \
            -v $(pwd)/users:/etc/dovecot/users \
            dovecot/dovecot:latest
          sleep 5
      - name: Run tests
        run: |
          chmod +x ./imaptest-x86_64-ubuntu-24.04
          for testfile in $(find src/tests -maxdepth 1 -type f ! -name "*.mbox"); do
              testname=$(basename "$testfile")
              mboxfile=${testfile}.mbox
              mbox_arg=""
              if [ -f "$mboxfile" ]; then
                  mbox_arg="-m $mboxfile"
              fi
              echo "Running test: $testname"
              ./imaptest-x86_64-ubuntu-24.04 -h 127.0.0.1 -p 1430 -u imaptest -P imaptest \
                        -c profile.conf $mbox_arg -t "$testfile"
          done
